-- MySQL Script generated by MySQL Workbench
-- Sat Aug 29 09:24:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema manuscriptcataloguer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manuscriptcataloguer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manuscriptcataloguer` DEFAULT CHARACTER SET utf8 ;
USE `manuscriptcataloguer` ;

-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`mss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`mss` (
  `id` INT NOT NULL,
  `catalogue_number` VARCHAR(45) NULL,
  `general_description` LONGTEXT NULL,
  `format` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`ms_sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`ms_sections` (
  `id` INT NOT NULL,
  `ms_id` INT NOT NULL,
  `from_page_no` INT NULL,
  `from_page_side` CHAR(1) NULL,
  `to_page_no` INT NULL,
  `to_page_side` CHAR(1) NULL,
  `title_ar` VARCHAR(300) NULL,
  `title_coptic` VARCHAR(300) NULL,
  `title_en` VARCHAR(300) NULL,
  PRIMARY KEY (`id`, `ms_id`),
  INDEX `ms_id_idx` (`ms_id` ASC) VISIBLE,
  CONSTRAINT `ms_id`
    FOREIGN KEY (`ms_id`)
    REFERENCES `manuscriptcataloguer`.`mss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`layout_of_text_ref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`layout_of_text_ref` (
  `id` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  `description` VARCHAR(150) NULL,
  `sample_img1_path` VARCHAR(45) NULL,
  `sample_img2_path` VARCHAR(45) NULL,
  `sample_img3_path` VARCHAR(45) NULL,
  `sample_img4_path` VARCHAR(45) NULL,
  `sample_img5_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`mss_layout_of_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`mss_layout_of_text` (
  `id` INT NOT NULL,
  `ms_id` INT NULL,
  `layout_of_text_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `ms_id_idx` (`ms_id` ASC) VISIBLE,
  INDEX `layout_of_text_id_idx` (`layout_of_text_id` ASC) VISIBLE,
  CONSTRAINT `ms_id`
    FOREIGN KEY (`ms_id`)
    REFERENCES `manuscriptcataloguer`.`mss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `layout_of_text_id`
    FOREIGN KEY (`layout_of_text_id`)
    REFERENCES `manuscriptcataloguer`.`layout_of_text_ref` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`ms_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`ms_pages` (
  `id` INT NOT NULL,
  `ms_section_id` INT NULL,
  `page_no` INT NULL,
  `page_side` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `ms_section_id_idx` (`ms_section_id` ASC) VISIBLE,
  CONSTRAINT `ms_section_id`
    FOREIGN KEY (`ms_section_id`)
    REFERENCES `manuscriptcataloguer`.`ms_sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`ms_prologues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`ms_prologues` (
  `id` INT NOT NULL,
  `ms_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `ms_id_idx` (`ms_id` ASC) VISIBLE,
  CONSTRAINT `ms_id`
    FOREIGN KEY (`ms_id`)
    REFERENCES `manuscriptcataloguer`.`mss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`ms_colophons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`ms_colophons` (
  `id` INT NOT NULL,
  `ms_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `ms_id_idx` (`ms_id` ASC) VISIBLE,
  CONSTRAINT `ms_id`
    FOREIGN KEY (`ms_id`)
    REFERENCES `manuscriptcataloguer`.`mss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`contributions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`contributions` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`contributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`contributors` (
  `id` INT NOT NULL,
  `name_ar` VARCHAR(100) NULL,
  `name_cop` VARCHAR(100) NULL,
  `name_en` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`mss_contributors_contributions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`mss_contributors_contributions` (
  `ms_id` INT NOT NULL,
  `contributor_id` INT NOT NULL,
  `contribution_id` INT NOT NULL,
  PRIMARY KEY (`ms_id`, `contribution_id`, `contributor_id`),
  INDEX `person_id_idx` (`contributor_id` ASC) VISIBLE,
  INDEX `contribution_id_idx` (`contribution_id` ASC) VISIBLE,
  CONSTRAINT `ms_id`
    FOREIGN KEY (`ms_id`)
    REFERENCES `manuscriptcataloguer`.`mss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_id`
    FOREIGN KEY (`contributor_id`)
    REFERENCES `manuscriptcataloguer`.`contributors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contribution_id`
    FOREIGN KEY (`contribution_id`)
    REFERENCES `manuscriptcataloguer`.`contributions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`scribal_errors_ref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`scribal_errors_ref` (
  `id` INT NOT NULL,
  `description` VARCHAR(150) NULL,
  `sample_img1_path` VARCHAR(45) NULL,
  `sample_img2_path` VARCHAR(45) NULL,
  `sample_img3_path` VARCHAR(45) NULL,
  `sample_img4_path` VARCHAR(45) NULL,
  `sample_img5_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`mss_scribal_errors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`mss_scribal_errors` (
  `id` INT NOT NULL,
  `ms_id` INT NULL,
  `scribal_error_id` INT NULL,
  `page_no` VARCHAR(5) NULL,
  `page_side` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `ms_id_idx` (`ms_id` ASC) VISIBLE,
  INDEX `scribal_error_id_idx` (`scribal_error_id` ASC) VISIBLE,
  CONSTRAINT `ms_id`
    FOREIGN KEY (`ms_id`)
    REFERENCES `manuscriptcataloguer`.`mss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scribal_error_id`
    FOREIGN KEY (`scribal_error_id`)
    REFERENCES `manuscriptcataloguer`.`scribal_errors_ref` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`construction_ref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`construction_ref` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`textual_punctuation_ref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`textual_punctuation_ref` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `sample_img1_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`textual_decoration_and_dividers_ref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`textual_decoration_and_dividers_ref` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `sample_img1_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`section_prologues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`section_prologues` (
  `id` INT NOT NULL,
  `ms_section_id` VARCHAR(45) NULL,
  `page_no` VARCHAR(45) NULL,
  `page_side` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`hands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`hands` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `sample_img1_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuscriptcataloguer`.`mss_hands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuscriptcataloguer`.`mss_hands` (
  `id` INT NOT NULL,
  `ms_id` INT NULL,
  `hand_id` INT NULL,
  `from_page_no` VARCHAR(45) NULL,
  `from_page_side` CHAR(1) NULL,
  `to_page_no` VARCHAR(45) NULL,
  `to_page_side` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `ms_id_idx` (`ms_id` ASC) VISIBLE,
  INDEX `hand_id_idx` (`hand_id` ASC) VISIBLE,
  CONSTRAINT `ms_id`
    FOREIGN KEY (`ms_id`)
    REFERENCES `manuscriptcataloguer`.`mss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hand_id`
    FOREIGN KEY (`hand_id`)
    REFERENCES `manuscriptcataloguer`.`hands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
